import tailwindcssAnimate from 'tailwindcss-animate'

const toneScale = (prefix) => ({
  50: `hsl(var(--${prefix}-50) / <alpha-value>)`,
  100: `hsl(var(--${prefix}-100) / <alpha-value>)`,
  200: `hsl(var(--${prefix}-200) / <alpha-value>)`,
  300: `hsl(var(--${prefix}-300) / <alpha-value>)`,
  400: `hsl(var(--${prefix}-400) / <alpha-value>)`,
  500: `hsl(var(--${prefix}-500) / <alpha-value>)`,
  600: `hsl(var(--${prefix}-600) / <alpha-value>)`,
  700: `hsl(var(--${prefix}-700) / <alpha-value>)`,
  800: `hsl(var(--${prefix}-800) / <alpha-value>)`,
  900: `hsl(var(--${prefix}-900) / <alpha-value>)`,
})

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      screens: {
        nav: '900px',
        insight: '1280px',
      },
      fontFamily: {
        sans: ['var(--font-family-base)'],
      },
      fontSize: {
        caption: ['var(--text-caption-size)', { lineHeight: 'var(--text-caption-line)' }],
        micro: ['var(--text-micro-size)', { lineHeight: 'var(--text-micro-line)' }],
        label: ['var(--text-label-size)', { lineHeight: 'var(--text-label-line)' }],
        body: ['var(--text-body-size)', { lineHeight: 'var(--text-body-line)' }],
        display: ['var(--text-display-size)', { lineHeight: 'var(--text-display-line)', letterSpacing: '-0.02em' }],
      },
      transitionDuration: {
        ui: 'var(--motion-duration-ui)',
        150: 'var(--motion-duration-fast)',
        200: '200ms',
        220: 'var(--motion-duration-base)',
        300: '300ms',
        320: 'var(--motion-duration-slow)',
        420: 'var(--motion-duration-slower)',
        500: 'var(--motion-duration-emphasis)',
        700: 'var(--motion-duration-long)',
      },
      spacing: {
        'sz-7': '0.4375rem',
        'sz-18': '1.125rem',
        'sz-22': '1.375rem',
        'sz-84': '5.25rem',
        'sz-86': '5.375rem',
        'sz-88': '5.5rem',
        'sz-110': '6.875rem',
        'sz-170': '10.625rem',
        'sz-180': '11.25rem',
        'sz-220': '13.75rem',
        'sz-260': '16.25rem',
        'sz-280': '17.5rem',
        'sz-290': '18.125rem',
        'sz-320': '20rem',
        'sz-340': '21.25rem',
        'sz-360': '22.5rem',
        'sz-420': '26.25rem',
        'sz-520': '32.5rem',
        'sz-560': '35rem',
        'sz-580': '36.25rem',
        'sz-720': '45rem',
        'sz-760': '47.5rem',
        'sz-1320': '82.5rem',
        'sz-1360': '85rem',
        'sz-1380': '86.25rem',
      },
      colors: {
        background: 'hsl(var(--background) / <alpha-value>)',
        foreground: 'hsl(var(--foreground) / <alpha-value>)',
        card: 'hsl(var(--card) / <alpha-value>)',
        'card-foreground': 'hsl(var(--card-foreground) / <alpha-value>)',
        muted: 'hsl(var(--muted) / <alpha-value>)',
        'muted-foreground': 'hsl(var(--muted-foreground) / <alpha-value>)',
        border: 'hsl(var(--border) / <alpha-value>)',
        primary: 'hsl(var(--primary) / <alpha-value>)',
        'primary-foreground': 'hsl(var(--primary-foreground) / <alpha-value>)',
        secondary: 'hsl(var(--secondary) / <alpha-value>)',
        'secondary-foreground': 'hsl(var(--secondary-foreground) / <alpha-value>)',
        accent: 'hsl(var(--accent) / <alpha-value>)',
        'accent-foreground': 'hsl(var(--accent-foreground) / <alpha-value>)',
        ring: 'hsl(var(--ring) / <alpha-value>)',
        focus: 'hsl(var(--focus) / <alpha-value>)',
        destructive: 'hsl(var(--destructive) / <alpha-value>)',
        'destructive-foreground': 'hsl(var(--destructive-foreground) / <alpha-value>)',
        'status-ok': 'hsl(var(--status-ok) / <alpha-value>)',
        'status-ok-muted': 'hsl(var(--status-ok-muted) / <alpha-value>)',
        'status-warn': 'hsl(var(--status-warn) / <alpha-value>)',
        'status-warn-muted': 'hsl(var(--status-warn-muted) / <alpha-value>)',
        'status-danger': 'hsl(var(--status-danger) / <alpha-value>)',
        'status-danger-muted': 'hsl(var(--status-danger-muted) / <alpha-value>)',
        brand: {
          orcid: 'hsl(var(--brand-orcid-green) / <alpha-value>)',
          google: {
            red: 'hsl(var(--brand-google-red) / <alpha-value>)',
            green: 'hsl(var(--brand-google-green) / <alpha-value>)',
            blue: 'hsl(var(--brand-google-blue) / <alpha-value>)',
            yellow: 'hsl(var(--brand-google-yellow) / <alpha-value>)',
          },
          microsoft: {
            red: 'hsl(var(--brand-microsoft-red) / <alpha-value>)',
            green: 'hsl(var(--brand-microsoft-green) / <alpha-value>)',
            blue: 'hsl(var(--brand-microsoft-blue) / <alpha-value>)',
            yellow: 'hsl(var(--brand-microsoft-yellow) / <alpha-value>)',
          },
        },
        slate: toneScale('tone-neutral'),
        gray: toneScale('tone-neutral'),
        zinc: toneScale('tone-neutral'),
        neutral: toneScale('tone-neutral'),
        stone: toneScale('tone-neutral'),
        emerald: toneScale('tone-positive'),
        green: toneScale('tone-positive'),
        amber: toneScale('tone-warning'),
        yellow: toneScale('tone-warning'),
        red: toneScale('tone-danger'),
        rose: toneScale('tone-danger'),
        orange: toneScale('tone-warning'),
        blue: toneScale('tone-accent'),
        indigo: toneScale('tone-accent'),
        cyan: toneScale('tone-accent'),
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      borderWidth: {
        3: '3px',
      },
    },
  },
  plugins: [tailwindcssAnimate],
}
