"""Extract records models — RHC, echocardiogram, CMR, CPEX."""

from datetime import datetime, timezone
from uuid import uuid4

from sqlalchemy import DateTime, Float, Integer, Text
from sqlalchemy.orm import Mapped, mapped_column

from research_os.db import Base


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


# ---------------------------------------------------------------------------
# RHC (41 columns)
# ---------------------------------------------------------------------------

class ExtractRhc(Base):
    __tablename__ = "extract_rhc"

    id: Mapped[str] = mapped_column(
        Text, primary_key=True, default=lambda: str(uuid4())
    )
    hn: Mapped[str] = mapped_column(Text, nullable=False, index=True)
    date_rhc: Mapped[str | None] = mapped_column(Text, nullable=True)
    pending: Mapped[int] = mapped_column(Integer, default=0)
    height: Mapped[float | None] = mapped_column(Float, nullable=True)
    weight: Mapped[float | None] = mapped_column(Float, nullable=True)
    ra_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    ra_a: Mapped[float | None] = mapped_column(Float, nullable=True)
    ra_v: Mapped[float | None] = mapped_column(Float, nullable=True)
    ra_o2_sat: Mapped[float | None] = mapped_column(Float, nullable=True)
    rv_systolic: Mapped[float | None] = mapped_column(Float, nullable=True)
    rv_diastolic: Mapped[float | None] = mapped_column(Float, nullable=True)
    rv_o2_sat: Mapped[float | None] = mapped_column(Float, nullable=True)
    pa_systolic: Mapped[float | None] = mapped_column(Float, nullable=True)
    pa_diastolic: Mapped[float | None] = mapped_column(Float, nullable=True)
    pa_mean: Mapped[float | None] = mapped_column(Float, nullable=True, index=True)
    pcwp_mean: Mapped[float | None] = mapped_column(Float, nullable=True, index=True)
    pcwp_a: Mapped[float | None] = mapped_column(Float, nullable=True)
    pcwp_v: Mapped[float | None] = mapped_column(Float, nullable=True)
    pa_o2_sat: Mapped[float | None] = mapped_column(Float, nullable=True)
    aorta_systolic: Mapped[float | None] = mapped_column(Float, nullable=True)
    aorta_diastolic: Mapped[float | None] = mapped_column(Float, nullable=True)
    aorta_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    aorta_o2_sat: Mapped[float | None] = mapped_column(Float, nullable=True)
    lv_systolic: Mapped[float | None] = mapped_column(Float, nullable=True)
    lv_diastolic: Mapped[float | None] = mapped_column(Float, nullable=True)
    cardiac_output: Mapped[float | None] = mapped_column(Float, nullable=True)
    cardiac_index: Mapped[float | None] = mapped_column(Float, nullable=True)
    pvr_wu: Mapped[float | None] = mapped_column(Float, nullable=True, index=True)
    pvr_dyn: Mapped[float | None] = mapped_column(Float, nullable=True)
    tpg: Mapped[float | None] = mapped_column(Float, nullable=True)
    rhc_comments: Mapped[str | None] = mapped_column(Text, nullable=True)
    source_file: Mapped[str | None] = mapped_column(Text, nullable=True)
    raw_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow
    )
    status: Mapped[str] = mapped_column(Text, default="Pending")
    rv_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    pcwp_o2_sat: Mapped[float | None] = mapped_column(Float, nullable=True)
    lv_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    lv_o2_sat: Mapped[float | None] = mapped_column(Float, nullable=True)
    status_date: Mapped[str | None] = mapped_column(Text, nullable=True)


# ---------------------------------------------------------------------------
# Echocardiogram (120 columns)
# ---------------------------------------------------------------------------

class ExtractEchocardiogram(Base):
    __tablename__ = "extract_echocardiogram"

    id: Mapped[str] = mapped_column(
        Text, primary_key=True, default=lambda: str(uuid4())
    )
    hn: Mapped[str] = mapped_column(Text, nullable=False, index=True)
    study_date: Mapped[str | None] = mapped_column(Text, nullable=True)
    report_date: Mapped[str | None] = mapped_column(Text, nullable=True)
    consultant: Mapped[str | None] = mapped_column(Text, nullable=True)
    ward_op: Mapped[str | None] = mapped_column(Text, nullable=True)
    study_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    rhythm: Mapped[str | None] = mapped_column(Text, nullable=True)
    hr: Mapped[float | None] = mapped_column(Float, nullable=True)
    bp_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    image_quality: Mapped[str | None] = mapped_column(Text, nullable=True)
    height: Mapped[float | None] = mapped_column(Float, nullable=True)
    weight: Mapped[float | None] = mapped_column(Float, nullable=True)
    bsa: Mapped[float | None] = mapped_column(Float, nullable=True)
    lv_size: Mapped[str | None] = mapped_column(Text, nullable=True)
    lv_wall: Mapped[str | None] = mapped_column(Text, nullable=True)
    lvh: Mapped[int | None] = mapped_column(Integer, nullable=True)
    rwma: Mapped[int | None] = mapped_column(Integer, nullable=True)
    lv_fn: Mapped[str | None] = mapped_column(Text, nullable=True)
    lvef: Mapped[float | None] = mapped_column(Float, nullable=True)
    gls: Mapped[float | None] = mapped_column(Float, nullable=True)
    mapse: Mapped[float | None] = mapped_column(Float, nullable=True)
    med_s: Mapped[float | None] = mapped_column(Float, nullable=True)
    lat_s: Mapped[float | None] = mapped_column(Float, nullable=True)
    sept_e: Mapped[float | None] = mapped_column(Float, nullable=True)
    lat_e: Mapped[float | None] = mapped_column(Float, nullable=True)
    avg_e_ep: Mapped[float | None] = mapped_column(Float, nullable=True)
    sept_e_ep: Mapped[float | None] = mapped_column(Float, nullable=True)
    mv_e: Mapped[float | None] = mapped_column(Float, nullable=True)
    mv_a: Mapped[float | None] = mapped_column(Float, nullable=True)
    e_a: Mapped[float | None] = mapped_column(Float, nullable=True)
    dt_ms: Mapped[float | None] = mapped_column(Float, nullable=True)
    diast_fn: Mapped[str | None] = mapped_column(Text, nullable=True)
    fill_press: Mapped[str | None] = mapped_column(Text, nullable=True)
    rv_size: Mapped[str | None] = mapped_column(Text, nullable=True)
    rv_fn: Mapped[str | None] = mapped_column(Text, nullable=True)
    tapse: Mapped[float | None] = mapped_column(Float, nullable=True)
    rv_s: Mapped[float | None] = mapped_column(Float, nullable=True)
    fac: Mapped[float | None] = mapped_column(Float, nullable=True)
    tr_vmax: Mapped[float | None] = mapped_column(Float, nullable=True)
    rvsp: Mapped[float | None] = mapped_column(Float, nullable=True)
    rap: Mapped[float | None] = mapped_column(Float, nullable=True)
    ivc_size: Mapped[str | None] = mapped_column(Text, nullable=True)
    ivc_coll: Mapped[str | None] = mapped_column(Text, nullable=True)
    ph_prob: Mapped[str | None] = mapped_column(Text, nullable=True)
    sept_flat: Mapped[int | None] = mapped_column(Integer, nullable=True)
    sept_bounce: Mapped[int | None] = mapped_column(Integer, nullable=True)
    d_shaped_lv: Mapped[int | None] = mapped_column(Integer, nullable=True)
    pa_dilated: Mapped[int | None] = mapped_column(Integer, nullable=True)
    peric_eff: Mapped[int | None] = mapped_column(Integer, nullable=True)
    ias_intact: Mapped[int | None] = mapped_column(Integer, nullable=True)
    shunt: Mapped[int | None] = mapped_column(Integer, nullable=True)
    la_size: Mapped[str | None] = mapped_column(Text, nullable=True)
    ra_size: Mapped[str | None] = mapped_column(Text, nullable=True)
    mv_desc: Mapped[str | None] = mapped_column(Text, nullable=True)
    ms_grade: Mapped[str | None] = mapped_column(Text, nullable=True)
    mr_grade: Mapped[str | None] = mapped_column(Text, nullable=True)
    tv_desc: Mapped[str | None] = mapped_column(Text, nullable=True)
    ts_grade: Mapped[str | None] = mapped_column(Text, nullable=True)
    tr_grade: Mapped[str | None] = mapped_column(Text, nullable=True)
    av_desc: Mapped[str | None] = mapped_column(Text, nullable=True)
    av_vmax: Mapped[float | None] = mapped_column(Float, nullable=True)
    av_pk_grad: Mapped[float | None] = mapped_column(Float, nullable=True)
    av_mn_grad: Mapped[float | None] = mapped_column(Float, nullable=True)
    ava: Mapped[float | None] = mapped_column(Float, nullable=True)
    as_grade: Mapped[str | None] = mapped_column(Text, nullable=True)
    ar_grade: Mapped[str | None] = mapped_column(Text, nullable=True)
    ar_pht: Mapped[float | None] = mapped_column(Float, nullable=True)
    pv_desc: Mapped[str | None] = mapped_column(Text, nullable=True)
    ps_grade: Mapped[str | None] = mapped_column(Text, nullable=True)
    pr_grade: Mapped[str | None] = mapped_column(Text, nullable=True)
    pat: Mapped[float | None] = mapped_column(Float, nullable=True)
    pv_vmax: Mapped[float | None] = mapped_column(Float, nullable=True)
    ao_root_desc: Mapped[str | None] = mapped_column(Text, nullable=True)
    asc_ao_desc: Mapped[str | None] = mapped_column(Text, nullable=True)
    lvidd: Mapped[float | None] = mapped_column(Float, nullable=True)
    lvids: Mapped[float | None] = mapped_column(Float, nullable=True)
    ivsd: Mapped[float | None] = mapped_column(Float, nullable=True)
    lvpwd: Mapped[float | None] = mapped_column(Float, nullable=True)
    lvedvi: Mapped[float | None] = mapped_column(Float, nullable=True)
    lvesvi: Mapped[float | None] = mapped_column(Float, nullable=True)
    rwt: Mapped[float | None] = mapped_column(Float, nullable=True)
    lvmi: Mapped[float | None] = mapped_column(Float, nullable=True)
    la_diam: Mapped[float | None] = mapped_column(Float, nullable=True)
    la_vol: Mapped[float | None] = mapped_column(Float, nullable=True)
    la_voli: Mapped[float | None] = mapped_column(Float, nullable=True)
    ra_area: Mapped[float | None] = mapped_column(Float, nullable=True)
    ra_areai: Mapped[float | None] = mapped_column(Float, nullable=True)
    rvd1: Mapped[float | None] = mapped_column(Float, nullable=True)
    rvd2: Mapped[float | None] = mapped_column(Float, nullable=True)
    rvd3: Mapped[float | None] = mapped_column(Float, nullable=True)
    rvot2: Mapped[float | None] = mapped_column(Float, nullable=True)
    ao_ann: Mapped[float | None] = mapped_column(Float, nullable=True)
    ao_sinus: Mapped[float | None] = mapped_column(Float, nullable=True)
    stj_mm: Mapped[float | None] = mapped_column(Float, nullable=True)
    asc_ao_prox: Mapped[float | None] = mapped_column(Float, nullable=True)
    asc_ao_mid: Mapped[float | None] = mapped_column(Float, nullable=True)
    ao_arch: Mapped[float | None] = mapped_column(Float, nullable=True)
    main_pa_mm: Mapped[float | None] = mapped_column(Float, nullable=True)
    lvot_diam: Mapped[float | None] = mapped_column(Float, nullable=True)
    lvot_vel: Mapped[float | None] = mapped_column(Float, nullable=True)
    lvot_vti: Mapped[float | None] = mapped_column(Float, nullable=True)
    dvi: Mapped[float | None] = mapped_column(Float, nullable=True)
    av_vti: Mapped[float | None] = mapped_column(Float, nullable=True)
    conclusion: Mapped[str | None] = mapped_column(Text, nullable=True)
    conc_items: Mapped[str | None] = mapped_column(Text, nullable=True)
    narrative: Mapped[str | None] = mapped_column(Text, nullable=True)
    meas_table: Mapped[str | None] = mapped_column(Text, nullable=True)
    uncertain: Mapped[str | None] = mapped_column(Text, nullable=True)
    ai_warnings: Mapped[str | None] = mapped_column(Text, nullable=True)
    ai_raw_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    reported_by: Mapped[str | None] = mapped_column(Text, nullable=True)
    ai_conf: Mapped[str | None] = mapped_column(Text, nullable=True)
    case_type: Mapped[str | None] = mapped_column(Text, nullable=True)
    primary_dx: Mapped[str | None] = mapped_column(Text, nullable=True)
    secondary_path: Mapped[str | None] = mapped_column(Text, nullable=True)
    source_file: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow
    )
    status: Mapped[str] = mapped_column(Text, default="Pending")
    status_date: Mapped[str | None] = mapped_column(Text, nullable=True)


# ---------------------------------------------------------------------------
# CMR (117 columns)
# ---------------------------------------------------------------------------

class ExtractCmr(Base):
    __tablename__ = "extract_cmr"

    id: Mapped[str] = mapped_column(
        Text, primary_key=True, default=lambda: str(uuid4())
    )
    hn: Mapped[str] = mapped_column(Text, nullable=False, index=True)
    date_cmr: Mapped[str | None] = mapped_column(Text, nullable=True)
    source_file: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow
    )
    status: Mapped[str] = mapped_column(Text, default="Pending")
    height: Mapped[str | None] = mapped_column(Text, nullable=True)
    weight: Mapped[str | None] = mapped_column(Text, nullable=True)
    heart_rate: Mapped[str | None] = mapped_column(Text, nullable=True)
    indication: Mapped[str | None] = mapped_column(Text, nullable=True)
    contrast: Mapped[str | None] = mapped_column(Text, nullable=True)
    stress: Mapped[str | None] = mapped_column(Text, nullable=True)
    flow: Mapped[str | None] = mapped_column(Text, nullable=True)
    cmr_class: Mapped[str | None] = mapped_column(Text, nullable=True)
    primary_dx: Mapped[str | None] = mapped_column(Text, nullable=True)
    secondary_dx: Mapped[str | None] = mapped_column(Text, nullable=True)
    conclusions: Mapped[str | None] = mapped_column(Text, nullable=True)
    lv_size: Mapped[str | None] = mapped_column(Text, nullable=True)
    lv_function: Mapped[str | None] = mapped_column(Text, nullable=True)
    lvef: Mapped[str | None] = mapped_column(Text, nullable=True)
    lvedv: Mapped[str | None] = mapped_column(Text, nullable=True)
    lvesv: Mapped[str | None] = mapped_column(Text, nullable=True)
    lvsv: Mapped[str | None] = mapped_column(Text, nullable=True)
    lvedvi: Mapped[str | None] = mapped_column(Text, nullable=True)
    lvesvi: Mapped[str | None] = mapped_column(Text, nullable=True)
    lvsvi: Mapped[str | None] = mapped_column(Text, nullable=True)
    lv_mass: Mapped[str | None] = mapped_column(Text, nullable=True)
    lvmi: Mapped[str | None] = mapped_column(Text, nullable=True)
    max_lv_wall: Mapped[str | None] = mapped_column(Text, nullable=True)
    lvh: Mapped[str | None] = mapped_column(Text, nullable=True)
    rwma: Mapped[str | None] = mapped_column(Text, nullable=True)
    mapse: Mapped[str | None] = mapped_column(Text, nullable=True)
    pcwp: Mapped[str | None] = mapped_column(Text, nullable=True)
    rv_size: Mapped[str | None] = mapped_column(Text, nullable=True)
    rv_function: Mapped[str | None] = mapped_column(Text, nullable=True)
    rvef: Mapped[str | None] = mapped_column(Text, nullable=True)
    rvedv: Mapped[str | None] = mapped_column(Text, nullable=True)
    rvesv: Mapped[str | None] = mapped_column(Text, nullable=True)
    rvsv: Mapped[str | None] = mapped_column(Text, nullable=True)
    rvedvi: Mapped[str | None] = mapped_column(Text, nullable=True)
    rvesvi: Mapped[str | None] = mapped_column(Text, nullable=True)
    rvsvi: Mapped[str | None] = mapped_column(Text, nullable=True)
    tapse: Mapped[str | None] = mapped_column(Text, nullable=True)
    la_size: Mapped[str | None] = mapped_column(Text, nullable=True)
    la_volume: Mapped[str | None] = mapped_column(Text, nullable=True)
    ra_size: Mapped[str | None] = mapped_column(Text, nullable=True)
    rap: Mapped[str | None] = mapped_column(Text, nullable=True)
    d_shaped_lv: Mapped[str | None] = mapped_column(Text, nullable=True)
    d_shape_phase: Mapped[str | None] = mapped_column(Text, nullable=True)
    septal_flattening: Mapped[str | None] = mapped_column(Text, nullable=True)
    flattening_phase: Mapped[str | None] = mapped_column(Text, nullable=True)
    septal_bounce: Mapped[str | None] = mapped_column(Text, nullable=True)
    ias_bowing: Mapped[str | None] = mapped_column(Text, nullable=True)
    ias_direction: Mapped[str | None] = mapped_column(Text, nullable=True)
    rv_lv_ratio: Mapped[str | None] = mapped_column(Text, nullable=True)
    mpa_size: Mapped[str | None] = mapped_column(Text, nullable=True)
    lpa_size: Mapped[str | None] = mapped_column(Text, nullable=True)
    rpa_size: Mapped[str | None] = mapped_column(Text, nullable=True)
    mpa_vortex: Mapped[str | None] = mapped_column(Text, nullable=True)
    mpa_flow: Mapped[str | None] = mapped_column(Text, nullable=True)
    ph: Mapped[str | None] = mapped_column(Text, nullable=True)
    native_t1: Mapped[str | None] = mapped_column(Text, nullable=True)
    t2: Mapped[str | None] = mapped_column(Text, nullable=True)
    t2_star: Mapped[str | None] = mapped_column(Text, nullable=True)
    ecv: Mapped[str | None] = mapped_column(Text, nullable=True)
    lge: Mapped[str | None] = mapped_column(Text, nullable=True)
    fibrosis: Mapped[str | None] = mapped_column(Text, nullable=True)
    rv_insertion_point_lge: Mapped[str | None] = mapped_column(Text, nullable=True)
    lge_pattern: Mapped[str | None] = mapped_column(Text, nullable=True)
    lge_location: Mapped[str | None] = mapped_column(Text, nullable=True)
    lge_transmurality: Mapped[str | None] = mapped_column(Text, nullable=True)
    perfusion_defect: Mapped[str | None] = mapped_column(Text, nullable=True)
    inducible_ischaemia: Mapped[str | None] = mapped_column(Text, nullable=True)
    fixed_defect: Mapped[str | None] = mapped_column(Text, nullable=True)
    reversible_defect: Mapped[str | None] = mapped_column(Text, nullable=True)
    perfusion_territory: Mapped[str | None] = mapped_column(Text, nullable=True)
    perfusion_coronary_territory: Mapped[str | None] = mapped_column(Text, nullable=True)
    ao_forward_volume: Mapped[str | None] = mapped_column(Text, nullable=True)
    ao_backward_volume: Mapped[str | None] = mapped_column(Text, nullable=True)
    asc_aorta: Mapped[str | None] = mapped_column(Text, nullable=True)
    ar_rf: Mapped[str | None] = mapped_column(Text, nullable=True)
    ar_volume: Mapped[str | None] = mapped_column(Text, nullable=True)
    ar_severity: Mapped[str | None] = mapped_column(Text, nullable=True)
    as_severity: Mapped[str | None] = mapped_column(Text, nullable=True)
    ao_vmax: Mapped[str | None] = mapped_column(Text, nullable=True)
    ao_mean_grad: Mapped[str | None] = mapped_column(Text, nullable=True)
    holo_diastolic_reversal: Mapped[str | None] = mapped_column(Text, nullable=True)
    mr_rf: Mapped[str | None] = mapped_column(Text, nullable=True)
    mr_volume: Mapped[str | None] = mapped_column(Text, nullable=True)
    mr_severity: Mapped[str | None] = mapped_column(Text, nullable=True)
    tr_rf: Mapped[str | None] = mapped_column(Text, nullable=True)
    tr_volume: Mapped[str | None] = mapped_column(Text, nullable=True)
    tr_severity: Mapped[str | None] = mapped_column(Text, nullable=True)
    pulmonary_forward_volume: Mapped[str | None] = mapped_column(Text, nullable=True)
    pulmonary_backward_volume: Mapped[str | None] = mapped_column(Text, nullable=True)
    pr_rf: Mapped[str | None] = mapped_column(Text, nullable=True)
    pr_volume: Mapped[str | None] = mapped_column(Text, nullable=True)
    pr_severity: Mapped[str | None] = mapped_column(Text, nullable=True)
    qp_qs: Mapped[str | None] = mapped_column(Text, nullable=True)
    pericardial_effusion: Mapped[str | None] = mapped_column(Text, nullable=True)
    pericardial_thickening: Mapped[str | None] = mapped_column(Text, nullable=True)
    pericardial_inflammation: Mapped[str | None] = mapped_column(Text, nullable=True)
    constrictive_physiology: Mapped[str | None] = mapped_column(Text, nullable=True)
    thrombus: Mapped[str | None] = mapped_column(Text, nullable=True)
    thrombus_location: Mapped[str | None] = mapped_column(Text, nullable=True)
    mass: Mapped[str | None] = mapped_column(Text, nullable=True)
    mass_location: Mapped[str | None] = mapped_column(Text, nullable=True)
    congenital: Mapped[str | None] = mapped_column(Text, nullable=True)
    congenital_detail: Mapped[str | None] = mapped_column(Text, nullable=True)
    cardiac_surgery: Mapped[str | None] = mapped_column(Text, nullable=True)
    surgery_detail: Mapped[str | None] = mapped_column(Text, nullable=True)
    device_prosthesis: Mapped[str | None] = mapped_column(Text, nullable=True)
    extracardiac_findings: Mapped[str | None] = mapped_column(Text, nullable=True)
    other_extractable_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    qc_notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    classification_note: Mapped[str | None] = mapped_column(Text, nullable=True)
    status_date: Mapped[str | None] = mapped_column(Text, nullable=True)
    measurements_json: Mapped[str | None] = mapped_column(Text, nullable=True)


# ---------------------------------------------------------------------------
# CPEX (7 columns)
# ---------------------------------------------------------------------------

class ExtractCpex(Base):
    __tablename__ = "extract_cpex"

    id: Mapped[str] = mapped_column(
        Text, primary_key=True, default=lambda: str(uuid4())
    )
    hn: Mapped[str] = mapped_column(Text, nullable=False, index=True)
    date_cpex: Mapped[str | None] = mapped_column(Text, nullable=True)
    source_file: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow
    )
    status: Mapped[str] = mapped_column(Text, default="Pending")
    status_date: Mapped[str | None] = mapped_column(Text, nullable=True)
