import { houseActions, houseChartColors, houseDividers, houseDrilldown, houseMotion, houseSurfaces, houseTypography } from '@/lib/house-style'

export const publicationsHouseHeadings = {
  title: houseTypography.title,
  sectionTitle: houseTypography.sectionTitle,
  h1: houseTypography.h1,
  h1Soft: houseTypography.h1Soft,
  h2: houseTypography.h2,
  h3: houseTypography.h3,
  label: houseTypography.label,
  text: houseTypography.text,
  textSoft: houseTypography.textSoft,
  metricSubtitle: houseTypography.metricSubtitle,
  metricDetail: houseTypography.metricDetail,
  metricNarrative: houseTypography.metricNarrative,
} as const

export const publicationsHouseSurfaces = {
  topPanel: houseSurfaces.topPanel,
  sectionPanel: houseSurfaces.sectionPanel,
  softPanel: houseSurfaces.softPanel,
  strongPanel: houseSurfaces.strongPanel,
  card: houseSurfaces.card,
  panelBare: houseSurfaces.panelBare,
  banner: houseSurfaces.banner,
  bannerInfo: houseSurfaces.bannerInfo,
  bannerSuccess: houseSurfaces.bannerSuccess,
  bannerWarning: houseSurfaces.bannerWarning,
  bannerDanger: houseSurfaces.bannerDanger,
  bannerPublications: houseSurfaces.bannerPublications,
  metricPill: houseSurfaces.metricPill,
  metricPillPublications: houseSurfaces.metricPillPublications,
  metricPillPublicationsRegular: houseSurfaces.metricPillPublicationsRegular,
  leftBorder: houseSurfaces.leftBorder,
  leftBorderPublications: houseSurfaces.leftBorderPublications,
  tableShell: houseSurfaces.tableShell,
  tableHead: houseSurfaces.tableHead,
  tableRow: houseSurfaces.tableRow,
} as const

export const publicationsHouseDividers = {
  borderSoft: houseDividers.borderSoft,
  fillSoft: houseDividers.fillSoft,
  strong: houseDividers.strong,
} as const

export const publicationsHouseMotion = {
  chartPanel: houseMotion.chartPanel,
  chartEnter: houseMotion.chartEnter,
  chartExit: houseMotion.chartExit,
  ringChartEnter: houseMotion.ringChartEnter,
  ringChartExit: houseMotion.ringChartExit,
  chartScaleLayer: houseMotion.chartScaleLayer,
  chartScaleTick: houseMotion.chartScaleTick,
  chartScaleAxisTitle: houseMotion.chartScaleAxisTitle,
  chartScaleMeanLine: houseMotion.chartScaleMeanLine,
  // TODO: Map to a dedicated delayed class when houseMotion exposes one again.
  chartScaleMeanLineDelayed: houseMotion.chartScaleMeanLine,
  toggleTrack: houseMotion.toggleTrack,
  toggleThumb: houseMotion.toggleThumb,
  toggleButton: houseMotion.toggleButton,
  toggleChartBar: houseMotion.toggleChartBar,
  toggleChartSwap: houseMotion.toggleChartSwap,
  toggleChartLabel: houseMotion.toggleChartLabel,
  labelTransition: houseMotion.labelTransition,
} as const

export const publicationsHouseCharts = {
  barAccent: houseChartColors.accentBar,
  barPositive: houseChartColors.positiveBar,
  barWarning: houseChartColors.warningBar,
  barNeutral: houseChartColors.neutralBar,
  barCurrent: houseChartColors.currentBar,
  gridLine: houseChartColors.gridLine,
  gridDashed: houseChartColors.gridLineDashed,
  gridLineSubtle: houseChartColors.gridLineSubtle,
  gridDashedSubtle: houseChartColors.gridLineDashedSubtle,
  meanLine: houseChartColors.meanLine,
  axisText: houseChartColors.axisText,
  axisTextTrend: houseChartColors.axisTextTrend,
  axisTitle: houseChartColors.axisTitle,
  axisLabel: houseChartColors.axisLabel,
  axisSubtext: houseChartColors.axisSubtext,
  axisWindowSubtext: houseChartColors.axisWindowSubtext,
  lineSoftSvg: houseChartColors.lineSoftSvg,
  ringTrackSvg: houseChartColors.ringTrackSvg,
  ringMainSvg: houseChartColors.ringMainSvg,
  ringSoftSvg: houseChartColors.ringSoftSvg,
  ringRemainderSvg: houseChartColors.ringRemainderSvg,
  ringThreshold50Svg: houseChartColors.ringThreshold50Svg,
  ringThreshold75Svg: houseChartColors.ringThreshold75Svg,
  ringThreshold90Svg: houseChartColors.ringThreshold90Svg,
  ringThreshold95Svg: houseChartColors.ringThreshold95Svg,
  ringThreshold99Svg: houseChartColors.ringThreshold99Svg,
  ringToggleLayout: houseChartColors.ringToggleLayout,
  ringToggleControl: houseChartColors.ringToggleControl,
  ringToggleVisual: houseChartColors.ringToggleVisual,
  ringCenterLabel: houseChartColors.ringCenterLabel,
  ringPanel: houseChartColors.ringPanel,
  ringSize: houseChartColors.ringSize,
  miniDonut: houseChartColors.miniDonut,
} as const

export const publicationsHouseActions = {
  sectionTools: houseActions.sectionTools,
  sectionToolsPublications: houseActions.sectionToolsPublications,
  sectionToolButton: houseActions.sectionToolButton,
  sectionToolToggle: houseActions.sectionToolToggle,
  sectionToolToggleOn: houseActions.sectionToolToggleOn,
  sectionToolToggleOff: houseActions.sectionToolToggleOff,
  sectionToolDivider: houseActions.sectionToolDivider,
  actionPill: houseActions.actionPill,
  actionPillPrimary: houseActions.actionPillPrimary,
  actionPillTableBodyText: houseActions.actionPillTableBodyText,
  actionPillIconGroup: houseActions.actionPillIconGroup,
  actionPillIcon: houseActions.actionPillIcon,
} as const

export const publicationsHouseDetail = {
  panel: 'house-publication-detail-panel',
  scroll: 'house-publication-detail-scroll',
  header: 'house-publication-detail-header',
  title: 'house-publication-detail-title',
  tabs: houseDrilldown.tabList,
  tab: houseDrilldown.tabTrigger,
  body: 'house-publication-detail-body',
  section: 'house-publication-detail-section',
  sectionLabel: 'house-publication-detail-label',
  metaChip: 'house-publication-detail-meta-chip',
  info: 'house-publication-detail-info',
} as const

export const publicationsHouseDrilldown = {
  sheet: houseDrilldown.sheet,
  sheetBody: houseDrilldown.sheetBody,
  tabTrigger: houseDrilldown.tabTrigger,
  tabList: houseDrilldown.tabList,
  sectionSeparator: houseDrilldown.sectionSeparator,
  sectionLabel: houseDrilldown.sectionLabel,
  summaryStatValue: houseDrilldown.summaryStatValue,
  summaryStatValueEmphasis: houseDrilldown.summaryStatValueEmphasis,
  summaryStatCard: houseDrilldown.summaryStatCard,
  summaryStatCardActive: houseDrilldown.summaryStatCardActive,
  summaryStatValueWrap: houseDrilldown.summaryStatValueWrap,
  sectionTitleSpacer: houseDrilldown.sectionTitleSpacer,
  placeholder: houseDrilldown.placeholder,
  alert: houseDrilldown.alert,
  microValue: houseDrilldown.microValue,
  hint: houseDrilldown.hint,
  caption: houseDrilldown.caption,
  chip: houseDrilldown.chip,
  chipActive: houseDrilldown.chipActive,
  action: houseDrilldown.action,
  row: houseDrilldown.row,
  rowActive: houseDrilldown.rowActive,
  progressTrack: houseDrilldown.progressTrack,
  progressFill: houseDrilldown.progressFill,
  statCard: houseDrilldown.statCard,
  statTitle: houseDrilldown.statTitle,
  statValue: houseDrilldown.statValue,
  statValueEmphasis: houseDrilldown.statValueEmphasis,
  axis: houseDrilldown.axis,
  range: houseDrilldown.range,
  badge: houseDrilldown.badge,
  badgePositive: houseDrilldown.badgePositive,
  badgeWarning: houseDrilldown.badgeWarning,
  badgeNeutral: houseDrilldown.badgeNeutral,
  note: houseDrilldown.note,
  noteSoft: houseDrilldown.noteSoft,
  dividerTop: houseDrilldown.dividerTop,
  chartGridSvg: houseDrilldown.chartGridSvg,
  chartAreaSvg: houseDrilldown.chartAreaSvg,
  chartMovingSvg: houseDrilldown.chartMovingSvg,
  chartMainSvg: houseDrilldown.chartMainSvg,
  chartTooltip: houseDrilldown.chartTooltip,
  skeletonBlock: houseDrilldown.skeletonBlock,
  barSelected: houseDrilldown.barSelected,
  barSelectedOutline: houseDrilldown.barSelectedOutline,
  tableRow: houseDrilldown.tableRow,
  tableEmpty: houseDrilldown.tableEmpty,
  toggleButtonMuted: houseDrilldown.toggleButtonMuted,
  summaryStatsGrid: houseDrilldown.summaryStatsGrid,
  summaryStatsGridCompact: houseDrilldown.summaryStatsGridCompact,
  summaryTrendChart: houseDrilldown.summaryTrendChart,
  summaryStatTitle: houseDrilldown.summaryStatTitle,
  chartControlsRow: houseDrilldown.chartControlsRow,
  chartControlsLeft: houseDrilldown.chartControlsLeft,
  chartMeta: houseDrilldown.chartMeta,
} as const
