export const CMR_BULLSEYE_CENTER = { x: 86, y: 88 } as const
export const CMR_BULLSEYE_ROTATION_DEG = 30
export const CMR_BULLSEYE_ROTATED_SEGMENT_MAX = 12
export const CMR_BULLSEYE_ROTATION_TRANSFORM = `rotate(${CMR_BULLSEYE_ROTATION_DEG} ${CMR_BULLSEYE_CENTER.x} ${CMR_BULLSEYE_CENTER.y})`
