export const houseTypography = {
  // Page title level.
  title: 'house-title',
  subtitle: 'house-subtitle',
  sectionTitle: 'house-section-title',
  sectionSubtitle: 'house-section-subtitle',

  // Primary heading level for section blocks.
  h1: 'house-h1',
  h1Soft: 'house-h1-soft',

  // Tile heading and compact heading levels.
  h2: 'house-h2',
  h3: 'house-h3',

  // Standard text styles.
  text: 'house-text',
  textSoft: 'house-text-soft',
  label: 'house-label',
  fieldLabel: 'house-field-label',
  fieldLabelInline: 'house-field-label-inline',
  fieldHelper: 'house-field-helper',
  buttonText: 'house-button-text',

  // Shared table text styles.
  tableHead: 'house-table-head-text',
  tableCell: 'house-table-cell-text',
} as const

export const houseSurfaces = {
  topPanel: 'house-panel-top',
  sectionPanel: 'house-panel-section',
  softPanel: 'house-panel-soft',
  card: 'house-panel-card',
  panelBare: 'house-panel-bare',
  banner: 'house-banner',
  bannerInfo: 'house-banner-info',
  bannerSuccess: 'house-banner-success',
  bannerWarning: 'house-banner-warning',
  bannerDanger: 'house-banner-danger',
  bannerPublications: 'house-banner-publications',
  metricPill: 'house-metric-pill',
  metricPillPublications: 'house-metric-pill-publications',
  leftBorder: 'house-left-border',
  leftBorderProfile: 'house-left-border-profile',
  leftBorderOverview: 'house-left-border-overview',
  leftBorderResearch: 'house-left-border-research',
  leftBorderAccount: 'house-left-border-account',
  leftBorderWorkspace: 'house-left-border-workspace',
  leftBorderData: 'house-left-border-data',
  leftBorderManuscript: 'house-left-border-manuscript',
  leftBorderGovernance: 'house-left-border-governance',
  leftBorderPublications: 'house-left-border-publications',
  tableShell: 'house-table-shell',
  tableHead: 'house-table-head',
  tableRow: 'house-table-row',
} as const

export const houseDividers = {
  borderSoft: 'house-divider-border-soft',
  fillSoft: 'house-divider-fill-soft',
  strong: 'house-divider-strong',
} as const

export const houseLayout = {
  pageHeader: 'house-page-header',
  sidebar: 'house-sidebar-shell',
  sidebarHeader: 'house-sidebar-header',
  sidebarSection: 'house-sidebar-section',
} as const

export const houseNavigation = {
  sectionLabel: 'house-nav-section-label',
  item: 'house-nav-item',
  itemActive: 'house-nav-item-active',
  itemOverview: 'house-nav-item-overview',
  itemResearch: 'house-nav-item-research',
  itemAccount: 'house-nav-item-account',
  itemWorkspace: 'house-nav-item-workspace',
  itemData: 'house-nav-item-data',
  itemManuscript: 'house-nav-item-manuscript',
  itemGovernance: 'house-nav-item-governance',
  itemMeta: 'house-nav-item-meta',
  itemCount: 'house-nav-item-count',
} as const

export const houseMotion = {
  chartPanel: 'house-chart-frame',
  chartEnter: 'house-motion-enter',
  chartExit: 'house-motion-exit',
  toggleTrack: 'house-toggle-track',
  toggleThumb: 'house-toggle-thumb',
  toggleButton: 'house-toggle-button',
  toggleChartBar: 'house-toggle-chart-bar',
  toggleChartSwap: 'house-toggle-chart-swap',
  toggleChartLabel: 'house-toggle-chart-label',
  labelTransition: 'house-label-transition',
} as const

export const houseForms = {
  input: 'house-input',
  select: 'house-dropdown',
  selectOption: 'house-dropdown-option',
  textarea: 'house-textarea',
  actionButton: 'house-button-action',
  actionButtonPrimary: 'house-button-action-primary',
  actionButtonGhost: 'house-button-action-ghost',
} as const

export const houseChartColors = {
  accentBar: 'house-chart-bar-accent',
  positiveBar: 'house-chart-bar-positive',
  warningBar: 'house-chart-bar-warning',
  neutralBar: 'house-chart-bar-neutral',
  currentBar: 'house-chart-bar-current',
  gridLine: 'house-chart-grid',
  gridLineDashed: 'house-chart-grid-dashed',
  axisText: 'house-chart-axis-text',
  axisSubtext: 'house-chart-axis-subtext',
  axisWindowSubtext: 'house-chart-window-subtext',
} as const

export const houseDrilldown = {
  sheet: 'house-drilldown-sheet',
  tabTrigger: 'house-drilldown-tab-trigger',
  placeholder: 'house-drilldown-placeholder',
  alert: 'house-drilldown-alert',
  microValue: 'house-drilldown-micro-value',
  hint: 'house-drilldown-hint',
  caption: 'house-drilldown-caption',
  chip: 'house-drilldown-chip',
  chipActive: 'house-drilldown-chip-active',
  action: 'house-drilldown-action',
  row: 'house-drilldown-row',
  rowActive: 'house-drilldown-row-active',
  progressTrack: 'house-drilldown-progress-track',
  progressFill: 'house-drilldown-progress-fill',
  statCard: 'house-drilldown-stat-card',
  statTitle: 'house-drilldown-stat-title',
  statValue: 'house-drilldown-stat-value',
  axis: 'house-drilldown-axis',
  range: 'house-drilldown-range',
  badge: 'house-drilldown-badge',
  badgePositive: 'house-drilldown-badge-positive',
  badgeWarning: 'house-drilldown-badge-warning',
  badgeNeutral: 'house-drilldown-badge-neutral',
  note: 'house-drilldown-note',
  noteSoft: 'house-drilldown-note-soft',
  dividerTop: 'house-drilldown-divider-top',
  chartGridSvg: 'house-drilldown-chart-grid-svg',
  chartAreaSvg: 'house-drilldown-chart-area-svg',
  chartMovingSvg: 'house-drilldown-chart-moving-svg',
  chartMainSvg: 'house-drilldown-chart-main-svg',
  barSelected: 'house-drilldown-breakdown-bar-selected',
  barSelectedOutline: 'house-drilldown-breakdown-bar-selected-outline',
  tableRow: 'house-drilldown-table-row',
  tableEmpty: 'house-drilldown-table-empty',
  toggleButtonMuted: 'house-drilldown-toggle-button-muted',
} as const

// Semantic map for element-level styling so pages can reference a single contract.
export const houseElements = {
  pageTitle: houseTypography.title,
  pageSubtitle: houseTypography.subtitle,
  sectionTitle: houseTypography.sectionTitle,
  sectionSubtitle: houseTypography.sectionSubtitle,
  metricTitle: houseTypography.h1,
  metricLabel: houseTypography.label,
  formLabel: houseTypography.fieldLabel,
  formLabelInline: houseTypography.fieldLabelInline,
  formHelper: houseTypography.fieldHelper,
  bodyText: houseTypography.text,
  bodyTextSoft: houseTypography.textSoft,
  buttonText: houseTypography.buttonText,
  formInput: houseForms.input,
  formSelect: houseForms.select,
  formSelectOption: houseForms.selectOption,
  formTextarea: houseForms.textarea,
  actionButton: houseForms.actionButton,
  actionButtonPrimary: houseForms.actionButtonPrimary,
  actionButtonGhost: houseForms.actionButtonGhost,
  topPanel: houseSurfaces.topPanel,
  sectionPanel: houseSurfaces.sectionPanel,
  softPanel: houseSurfaces.softPanel,
  card: houseSurfaces.card,
  panelBare: houseSurfaces.panelBare,
  banner: houseSurfaces.banner,
  bannerInfo: houseSurfaces.bannerInfo,
  bannerSuccess: houseSurfaces.bannerSuccess,
  bannerWarning: houseSurfaces.bannerWarning,
  bannerDanger: houseSurfaces.bannerDanger,
  bannerPublications: houseSurfaces.bannerPublications,
  metricPill: houseSurfaces.metricPill,
  metricPillPublications: houseSurfaces.metricPillPublications,
  leftBorder: houseSurfaces.leftBorder,
  leftBorderProfile: houseSurfaces.leftBorderProfile,
  leftBorderOverview: houseSurfaces.leftBorderOverview,
  leftBorderResearch: houseSurfaces.leftBorderResearch,
  leftBorderAccount: houseSurfaces.leftBorderAccount,
  leftBorderWorkspace: houseSurfaces.leftBorderWorkspace,
  leftBorderData: houseSurfaces.leftBorderData,
  leftBorderManuscript: houseSurfaces.leftBorderManuscript,
  leftBorderGovernance: houseSurfaces.leftBorderGovernance,
  leftBorderPublications: houseSurfaces.leftBorderPublications,
  dividerBorderSoft: houseDividers.borderSoft,
  dividerFillSoft: houseDividers.fillSoft,
  dividerStrong: houseDividers.strong,
  pageHeader: houseLayout.pageHeader,
  sidebar: houseLayout.sidebar,
  sidebarHeader: houseLayout.sidebarHeader,
  sidebarSection: houseLayout.sidebarSection,
  navSectionLabel: houseNavigation.sectionLabel,
  navItem: houseNavigation.item,
  navItemActive: houseNavigation.itemActive,
  navItemOverview: houseNavigation.itemOverview,
  navItemResearch: houseNavigation.itemResearch,
  navItemAccount: houseNavigation.itemAccount,
  navItemWorkspace: houseNavigation.itemWorkspace,
  navItemData: houseNavigation.itemData,
  navItemManuscript: houseNavigation.itemManuscript,
  navItemGovernance: houseNavigation.itemGovernance,
  navItemMeta: houseNavigation.itemMeta,
  navItemCount: houseNavigation.itemCount,
  tableShell: houseSurfaces.tableShell,
  tableHead: houseSurfaces.tableHead,
  tableRow: houseSurfaces.tableRow,
  chartPanel: houseMotion.chartPanel,
  toggleChartBar: houseMotion.toggleChartBar,
  toggleChartSwap: houseMotion.toggleChartSwap,
  toggleChartLabel: houseMotion.toggleChartLabel,
  chartGrid: houseChartColors.gridLine,
  chartGridDashed: houseChartColors.gridLineDashed,
  chartAxisText: houseChartColors.axisText,
  chartAxisSubtext: houseChartColors.axisSubtext,
  chartAxisWindowSubtext: houseChartColors.axisWindowSubtext,
  drilldownSheet: houseDrilldown.sheet,
  drilldownTabTrigger: houseDrilldown.tabTrigger,
  drilldownPlaceholder: houseDrilldown.placeholder,
  drilldownAlert: houseDrilldown.alert,
  drilldownMicroValue: houseDrilldown.microValue,
  drilldownHint: houseDrilldown.hint,
  drilldownCaption: houseDrilldown.caption,
  drilldownChip: houseDrilldown.chip,
  drilldownChipActive: houseDrilldown.chipActive,
  drilldownAction: houseDrilldown.action,
  drilldownRow: houseDrilldown.row,
  drilldownRowActive: houseDrilldown.rowActive,
  drilldownProgressTrack: houseDrilldown.progressTrack,
  drilldownProgressFill: houseDrilldown.progressFill,
  drilldownStatCard: houseDrilldown.statCard,
  drilldownStatTitle: houseDrilldown.statTitle,
  drilldownStatValue: houseDrilldown.statValue,
  drilldownAxis: houseDrilldown.axis,
  drilldownRange: houseDrilldown.range,
  drilldownBadge: houseDrilldown.badge,
  drilldownBadgePositive: houseDrilldown.badgePositive,
  drilldownBadgeWarning: houseDrilldown.badgeWarning,
  drilldownBadgeNeutral: houseDrilldown.badgeNeutral,
  drilldownNote: houseDrilldown.note,
  drilldownNoteSoft: houseDrilldown.noteSoft,
  drilldownDividerTop: houseDrilldown.dividerTop,
  drilldownChartGridSvg: houseDrilldown.chartGridSvg,
  drilldownChartAreaSvg: houseDrilldown.chartAreaSvg,
  drilldownChartMovingSvg: houseDrilldown.chartMovingSvg,
  drilldownChartMainSvg: houseDrilldown.chartMainSvg,
  drilldownBarSelected: houseDrilldown.barSelected,
  drilldownBarSelectedOutline: houseDrilldown.barSelectedOutline,
  drilldownTableRow: houseDrilldown.tableRow,
  drilldownTableEmpty: houseDrilldown.tableEmpty,
  drilldownToggleButtonMuted: houseDrilldown.toggleButtonMuted,
} as const
