export const houseTypography = {
  // Page title level.
  title: 'house-title',
  subtitle: 'house-subtitle',
  titleExpander: 'house-title-expander',
  
  // Drilldown panel header (title scaled for side-panel context)
  drilldownTitle: 'house-drilldown-title-scaled',
  // Keep subtitle/expander canonical to match page headers
  drilldownTitleExpander: 'house-title-expander',

  sectionTitle: 'house-section-title',
  sectionSubtitle: 'house-section-subtitle',

  // Primary heading level for section blocks.
  h1: 'house-h1',
  h1Soft: 'house-h1-soft',

  // Tile heading and compact heading levels.
  h2: 'house-h2',
  h3: 'house-h3',

  // Standard text styles.
  text: 'house-text',
  textSoft: 'house-text-soft',
  metricSubtitle: 'house-metric-subtitle',
  metricDetail: 'house-metric-detail',
  metricNarrative: 'house-metric-narrative',
  metricTileTitle: 'house-metric-tile-title',
  metricTileValue: 'house-metric-tile-value',
  label: 'house-label',
  fieldLabel: 'house-field-label',
  fieldLabelInline: 'house-field-label-inline',
  fieldHelper: 'house-field-helper',
  buttonText: 'house-button-text',

  // Shared table text styles.
  tableHead: 'house-table-head-text',
  tableCell: 'house-table-cell-text',
} as const

export const houseSurfaces = {
  topPanel: 'house-panel-top',
  sectionPanel: 'house-panel-section',
  softPanel: 'house-panel-soft',
  strongPanel: 'house-panel-strong',
  card: 'house-panel-card',
  panelBare: 'house-panel-bare',
  banner: 'house-banner',
  bannerInfo: 'house-banner-info',
  bannerSuccess: 'house-banner-success',
  bannerWarning: 'house-banner-warning',
  bannerDanger: 'house-banner-danger',
  bannerPublications: 'house-banner-publications',
  metricPill: 'house-metric-pill',
  metricPillPublications: 'house-metric-pill-publications',
  metricPillPublicationsRegular: 'house-metric-pill-publications-regular',
  leftBorder: 'house-left-border',
  leftBorderProfile: 'house-left-border-profile',
  leftBorderOverview: 'house-left-border-overview',
  leftBorderResearch: 'house-left-border-research',
  leftBorderAccount: 'house-left-border-account',
  leftBorderWorkspace: 'house-left-border-workspace',
  leftBorderData: 'house-left-border-data',
  leftBorderManuscript: 'house-left-border-manuscript',
  leftBorderGovernance: 'house-left-border-governance',
  leftBorderPublications: 'house-left-border-publications',
  leftBorderLearningCentre: 'house-left-border-learning-centre',
  leftBorderOpportunities: 'house-left-border-opportunities',
  tableShell: 'house-table-shell',
  tableHead: 'house-table-head',
  tableRow: 'house-table-row',
} as const

export const houseDividers = {
  borderSoft: 'house-divider-border-soft',
  fillSoft: 'house-divider-fill-soft',
  strong: 'house-divider-strong',
} as const

export const houseLayout = {
  pageHeader: 'house-page-header',
  pageMainContent: 'house-page-main-content',
  mainTitleBlock: 'house-main-title-block',
  mainHeadingBlock: 'house-main-heading-block',
  mainSubheadingBlock: 'house-main-subheading-block',
  mainSectionHeadingRow: 'house-main-section-heading-row',
  sectionAnchor: 'house-section-anchor',
  separatorLeftPanelSubheadingToContent: 'house-separator-left-panel-subheading-to-content',
  separatorLeftPanelContentToSubheading: 'house-separator-left-panel-content-to-subheading',
  sidebarFrame: 'house-sidebar-frame',
  sidebar: 'house-sidebar-shell',
  sidebarScroll: 'house-sidebar-scroll',
  sidebarHeader: 'house-sidebar-header',
  sidebarBody: 'house-sidebar-body',
  sidebarSection: 'house-sidebar-section',
} as const

export const houseNavigation = {
  sectionLabel: 'house-nav-section-label',
  list: 'house-nav-list',
  item: 'house-nav-item',
  itemLabel: 'house-nav-item-label',
  itemActive: 'house-nav-item-active',
  itemOverview: 'house-nav-item-overview',
  itemResearch: 'house-nav-item-research',
  itemAccount: 'house-nav-item-account',
  itemWorkspace: 'house-nav-item-workspace',
  itemData: 'house-nav-item-data',
  itemManuscript: 'house-nav-item-manuscript',
  itemGovernance: 'house-nav-item-governance',
  itemLearningCentre: 'house-nav-item-learning-centre',
  itemOpportunities: 'house-nav-item-opportunities',
  itemMetaGroup: 'house-nav-item-meta-group',
  itemMeta: 'house-nav-item-meta',
  itemCount: 'house-nav-item-count',
} as const

export const houseMotion = {
  chartPanel: 'house-chart-frame',
  chartSeriesByKey: 'house-chart-series-by-key',
  chartSeriesBySlot: 'house-chart-series-by-slot',
  chartEnter: 'house-motion-enter',
  chartExit: 'house-motion-exit',
  ringChartEnter: 'house-motion-static-enter',
  ringChartExit: 'house-motion-static-exit',
  chartScaleLayer: 'house-chart-scale-layer',
  chartScaleTick: 'house-chart-scale-tick',
  chartScaleAxisTitle: 'house-chart-scale-axis-title',
  chartScaleMeanLine: 'house-chart-scale-mean-line',
  toggleTrack: 'house-toggle-track',
  toggleThumb: 'house-toggle-thumb',
  toggleButton: 'house-toggle-button',
  toggleChartBar: 'house-toggle-chart-bar',
  toggleChartLine: 'house-toggle-chart-line',
  toggleChartMorph: 'house-toggle-chart-morph',
  toggleChartSwap: 'house-toggle-chart-swap',
  toggleChartLabel: 'house-toggle-chart-label',
  labelTransition: 'house-label-transition',
} as const

export const houseForms = {
  input: 'house-input',
  select: 'house-dropdown',
  selectOption: 'house-dropdown-option',
  textarea: 'house-textarea',
  actionButton: 'house-button-action',
  actionButtonPrimary: 'house-button-action-primary',
  actionButtonGhost: 'house-button-action-ghost',
  actionButtonSuccess: 'house-button-action-success',
  actionButtonDanger: 'house-button-action-danger',
} as const

export const houseActions = {
  sectionTools: 'house-section-tools',
  sectionToolsPublications: 'house-section-tools-publications',
  sectionToolsWorkspace: 'house-section-tools-workspace',
  sectionToolsData: 'house-section-tools-data',
  sectionToolButton: 'house-section-tool-button',
  sectionToolToggle: 'house-section-tool-toggle',
  sectionToolToggleOn: 'house-section-tool-toggle-on',
  sectionToolToggleOff: 'house-section-tool-toggle-off',
  sectionToolDivider: 'house-section-tool-divider',
  actionPill: 'house-publications-actions',
  actionPillPrimary: 'house-publications-action-primary',
  actionPillTableBodyText: 'house-action-pill-table-body-text',
  actionPillIconGroup: 'house-publications-action-icons',
  actionPillIcon: 'house-publications-action-icon',
} as const

export const houseTables = {
  filterInput: 'house-table-filter-input',
  filterSelect: 'house-table-filter-select',
  sortTrigger: 'house-table-sort-trigger',
} as const

export const houseCollaborators = {
  listShell: 'house-collaborator-list-shell',
  listViewport: 'house-collaborator-list-viewport',
  listViewportCompact: 'house-collaborator-list-viewport-compact',
  listBody: 'house-collaborator-list-body',
  candidate: 'house-collaborator-candidate',
  candidateSelected: 'house-collaborator-candidate-selected',
  candidateIdle: 'house-collaborator-candidate-idle',
  candidateMeta: 'house-collaborator-candidate-meta',
  candidateSource: 'house-collaborator-candidate-source',
  chip: 'house-collaborator-chip',
  chipActive: 'house-collaborator-chip-active',
  chipPending: 'house-collaborator-chip-pending',
  chipRemoved: 'house-collaborator-chip-removed',
  chipManageable: 'house-collaborator-chip-manageable',
  chipReadOnly: 'house-collaborator-chip-readonly',
  chipAction: 'house-collaborator-chip-action',
  actionIcon: 'house-collaborator-action-icon',
  actionIconAdd: 'house-collaborator-action-icon-add',
  actionIconConfirm: 'house-collaborator-action-icon-confirm',
  actionIconEdit: 'house-collaborator-action-icon-edit',
  actionIconRemove: 'house-collaborator-action-icon-remove',
  actionIconRestore: 'house-collaborator-action-icon-restore',
} as const

export const houseChartColors = {
  accentBar: 'house-chart-bar-accent',
  positiveBar: 'house-chart-bar-positive',
  warningBar: 'house-chart-bar-warning',
  neutralBar: 'house-chart-bar-neutral',
  currentBar: 'house-chart-bar-current',
  gridLine: 'house-chart-grid',
  gridLineDashed: 'house-chart-grid-dashed',
  gridLineSubtle: 'house-chart-grid-subtle',
  gridLineDashedSubtle: 'house-chart-grid-dashed-subtle',
  meanLine: 'house-chart-mean-line',
  axisText: 'house-chart-axis-text',
  axisTextTrend: 'house-chart-axis-text-trend',
  axisTitle: 'house-chart-axis-title',
  axisLabel: 'house-chart-axis-label',
  axisSubtext: 'house-chart-axis-subtext',
  axisPeriodTag: 'house-chart-axis-period-tag',
  axisWindowSubtext: 'house-chart-window-subtext',
  lineSoftSvg: 'house-chart-line-soft-svg',
  ringTrackSvg: 'house-chart-ring-track-svg',
  ringMainSvg: 'house-chart-ring-main-svg',
  ringSoftSvg: 'house-chart-ring-soft-svg',
  ringRemainderSvg: 'house-chart-ring-remainder-svg',
  ringThreshold50Svg: 'house-chart-ring-threshold-50-svg',
  ringThreshold75Svg: 'house-chart-ring-threshold-75-svg',
  ringThreshold90Svg: 'house-chart-ring-threshold-90-svg',
  ringThreshold95Svg: 'house-chart-ring-threshold-95-svg',
  ringThreshold99Svg: 'house-chart-ring-threshold-99-svg',
  ringToggleLayout: 'house-chart-ring-toggle-layout',
  ringToggleControl: 'house-chart-ring-toggle-control',
  ringToggleVisual: 'house-chart-ring-toggle-visual',
  ringCenterLabel: 'house-chart-ring-center-label',
  ringPanel: 'house-chart-ring-panel',
  ringSize: 'house-chart-ring-size',
  miniDonut: 'house-chart-mini-donut',
} as const

export const houseDrilldown = {
  sheet: 'house-drilldown-sheet',
  sheetBody: 'house-drilldown-sheet-body',
  titleBlock: 'house-drilldown-title-block',
  headingBlock: 'house-drilldown-heading-block',
  subheadingBlock: 'house-drilldown-subheading-block',
  contentBlock: 'house-drilldown-content-block',
  title: 'house-drilldown-title',
  titleExpander: 'house-drilldown-title-expander',
  overline: 'house-drilldown-overline',
  sectionLabel: 'house-drilldown-section-label',
  tabTrigger: 'house-drilldown-tab-trigger',
  tabList: 'house-drilldown-tab-list',
  placeholder: 'house-drilldown-placeholder',
  alert: 'house-drilldown-alert',
  microValue: 'house-drilldown-micro-value',
  hint: 'house-drilldown-hint',
  caption: 'house-drilldown-caption',
  chip: 'house-drilldown-chip',
  chipActive: 'house-drilldown-chip-active',
  action: 'house-drilldown-action',
  row: 'house-drilldown-row',
  rowActive: 'house-drilldown-row-active',
  progressTrack: 'house-drilldown-progress-track',
  progressFill: 'house-drilldown-progress-fill',
  statCard: 'house-drilldown-stat-card',
  statTitle: 'house-drilldown-stat-title',
  statValue: 'house-drilldown-stat-value',
  valuePositive: 'house-drilldown-value-positive',
  valueNegative: 'house-drilldown-value-negative',
  statValueEmphasis: 'house-drilldown-stat-value-emphasis',
  axis: 'house-drilldown-axis',
  range: 'house-drilldown-range',
  badge: 'house-drilldown-badge',
  badgePositive: 'house-drilldown-badge-positive',
  badgeWarning: 'house-drilldown-badge-warning',
  badgeNeutral: 'house-drilldown-badge-neutral',
  note: 'house-drilldown-note',
  noteSoft: 'house-drilldown-note-soft',
  noteWarning: 'house-drilldown-note-warning',
  link: 'house-drilldown-link',
  owner: 'house-drilldown-owner',
  dividerTop: 'house-drilldown-divider-top',
  fileDrop: 'house-drilldown-file-drop',
  fileDropActive: 'house-drilldown-file-drop-active',
  chartGridSvg: 'house-drilldown-chart-grid-svg',
  chartAreaSvg: 'house-drilldown-chart-area-svg',
  chartMovingSvg: 'house-drilldown-chart-moving-svg',
  chartMainSvg: 'house-drilldown-chart-main-svg',
  chartTooltip: 'house-drilldown-chart-tooltip',
  summaryStatValue: 'house-drilldown-summary-stat-value',
  summaryStatValueEmphasis: 'house-drilldown-summary-stat-value-emphasis',
  summaryStatCard: 'house-drilldown-summary-stat-card',
  summaryStatCardActive: 'house-drilldown-summary-stat-card-active',
  summaryStatValueWrap: 'house-drilldown-summary-stat-value-wrap',
  skeletonBlock: 'house-drilldown-skeleton-block',
  barSelected: 'house-drilldown-breakdown-bar-selected',
  barSelectedOutline: 'house-drilldown-breakdown-bar-selected-outline',
  tableRow: 'house-drilldown-table-row',
  tableEmpty: 'house-drilldown-table-empty',
  toggleButtonMuted: 'house-drilldown-toggle-button-muted',
  collapsibleSection: 'house-drilldown-collapsible-section',
  collapsibleEntity: 'house-drilldown-collapsible-entity',
  summaryStatsGrid: 'house-drilldown-summary-stats-grid',
  summaryStatsGridCompact: 'house-drilldown-summary-stats-grid-compact',
  summaryTrendChart: 'house-drilldown-summary-trend-chart',
  summaryStatTitle: 'house-drilldown-summary-stat-title',
  chartControlsRow: 'house-drilldown-chart-controls-row',
  chartControlsLeft: 'house-drilldown-chart-controls-left',
  chartMeta: 'house-drilldown-chart-meta',
} as const

// Semantic map for element-level styling so pages can reference a single contract.
export const houseElements = {
  pageTitle: houseTypography.title,
  pageSubtitle: houseTypography.subtitle,
  pageTitleExpander: houseTypography.titleExpander,
  sectionTitle: houseTypography.sectionTitle,
  sectionSubtitle: houseTypography.sectionSubtitle,
  metricTitle: houseTypography.h1,
  metricLabel: houseTypography.label,
  formLabel: houseTypography.fieldLabel,
  formLabelInline: houseTypography.fieldLabelInline,
  formHelper: houseTypography.fieldHelper,
  bodyText: houseTypography.text,
  bodyTextSoft: houseTypography.textSoft,
  metricSubtitle: houseTypography.metricSubtitle,
  metricDetail: houseTypography.metricDetail,
  metricNarrative: houseTypography.metricNarrative,
  buttonText: houseTypography.buttonText,
  formInput: houseForms.input,
  formSelect: houseForms.select,
  formSelectOption: houseForms.selectOption,
  formTextarea: houseForms.textarea,
  actionButton: houseForms.actionButton,
  actionButtonPrimary: houseForms.actionButtonPrimary,
  actionButtonGhost: houseForms.actionButtonGhost,
  actionButtonSuccess: houseForms.actionButtonSuccess,
  actionButtonDanger: houseForms.actionButtonDanger,
  sectionTools: houseActions.sectionTools,
  sectionToolsPublications: houseActions.sectionToolsPublications,
  sectionToolsWorkspace: houseActions.sectionToolsWorkspace,
  sectionToolsData: houseActions.sectionToolsData,
  sectionToolButton: houseActions.sectionToolButton,
  sectionToolToggle: houseActions.sectionToolToggle,
  sectionToolToggleOn: houseActions.sectionToolToggleOn,
  sectionToolToggleOff: houseActions.sectionToolToggleOff,
  sectionToolDivider: houseActions.sectionToolDivider,
  actionPill: houseActions.actionPill,
  actionPillPrimary: houseActions.actionPillPrimary,
  actionPillTableBodyText: houseActions.actionPillTableBodyText,
  actionPillIconGroup: houseActions.actionPillIconGroup,
  actionPillIcon: houseActions.actionPillIcon,
  tableFilterInput: houseTables.filterInput,
  tableFilterSelect: houseTables.filterSelect,
  tableSortTrigger: houseTables.sortTrigger,
  collaboratorListShell: houseCollaborators.listShell,
  collaboratorListViewport: houseCollaborators.listViewport,
  collaboratorListViewportCompact: houseCollaborators.listViewportCompact,
  collaboratorListBody: houseCollaborators.listBody,
  collaboratorCandidate: houseCollaborators.candidate,
  collaboratorCandidateSelected: houseCollaborators.candidateSelected,
  collaboratorCandidateIdle: houseCollaborators.candidateIdle,
  collaboratorCandidateMeta: houseCollaborators.candidateMeta,
  collaboratorCandidateSource: houseCollaborators.candidateSource,
  collaboratorChip: houseCollaborators.chip,
  collaboratorChipActive: houseCollaborators.chipActive,
  collaboratorChipPending: houseCollaborators.chipPending,
  collaboratorChipRemoved: houseCollaborators.chipRemoved,
  collaboratorChipManageable: houseCollaborators.chipManageable,
  collaboratorChipReadOnly: houseCollaborators.chipReadOnly,
  collaboratorChipAction: houseCollaborators.chipAction,
  collaboratorActionIcon: houseCollaborators.actionIcon,
  collaboratorActionIconAdd: houseCollaborators.actionIconAdd,
  collaboratorActionIconConfirm: houseCollaborators.actionIconConfirm,
  collaboratorActionIconEdit: houseCollaborators.actionIconEdit,
  collaboratorActionIconRemove: houseCollaborators.actionIconRemove,
  collaboratorActionIconRestore: houseCollaborators.actionIconRestore,
  topPanel: houseSurfaces.topPanel,
  sectionPanel: houseSurfaces.sectionPanel,
  softPanel: houseSurfaces.softPanel,
  strongPanel: houseSurfaces.strongPanel,
  card: houseSurfaces.card,
  panelBare: houseSurfaces.panelBare,
  banner: houseSurfaces.banner,
  bannerInfo: houseSurfaces.bannerInfo,
  bannerSuccess: houseSurfaces.bannerSuccess,
  bannerWarning: houseSurfaces.bannerWarning,
  bannerDanger: houseSurfaces.bannerDanger,
  bannerPublications: houseSurfaces.bannerPublications,
  metricPill: houseSurfaces.metricPill,
  metricPillPublications: houseSurfaces.metricPillPublications,
  metricPillPublicationsRegular: houseSurfaces.metricPillPublicationsRegular,
  leftBorder: houseSurfaces.leftBorder,
  leftBorderProfile: houseSurfaces.leftBorderProfile,
  leftBorderOverview: houseSurfaces.leftBorderOverview,
  leftBorderResearch: houseSurfaces.leftBorderResearch,
  leftBorderAccount: houseSurfaces.leftBorderAccount,
  leftBorderWorkspace: houseSurfaces.leftBorderWorkspace,
  leftBorderData: houseSurfaces.leftBorderData,
  leftBorderManuscript: houseSurfaces.leftBorderManuscript,
  leftBorderGovernance: houseSurfaces.leftBorderGovernance,
  leftBorderPublications: houseSurfaces.leftBorderPublications,
  leftBorderLearningCentre: houseSurfaces.leftBorderLearningCentre,
  leftBorderOpportunities: houseSurfaces.leftBorderOpportunities,
  dividerBorderSoft: houseDividers.borderSoft,
  dividerFillSoft: houseDividers.fillSoft,
  dividerStrong: houseDividers.strong,
  pageHeader: houseLayout.pageHeader,
  mainTitleBlock: houseLayout.mainTitleBlock,
  mainHeadingBlock: houseLayout.mainHeadingBlock,
  mainSubheadingBlock: houseLayout.mainSubheadingBlock,
  mainSectionHeadingRow: houseLayout.mainSectionHeadingRow,
  leftPanelSeparatorSubheadingToContent: houseLayout.separatorLeftPanelSubheadingToContent,
  leftPanelSeparatorContentToSubheading: houseLayout.separatorLeftPanelContentToSubheading,
  sidebarFrame: houseLayout.sidebarFrame,
  sidebar: houseLayout.sidebar,
  sidebarScroll: houseLayout.sidebarScroll,
  sidebarHeader: houseLayout.sidebarHeader,
  sidebarBody: houseLayout.sidebarBody,
  sidebarSection: houseLayout.sidebarSection,
  navSectionLabel: houseNavigation.sectionLabel,
  navList: houseNavigation.list,
  navItem: houseNavigation.item,
  navItemLabel: houseNavigation.itemLabel,
  navItemActive: houseNavigation.itemActive,
  navItemOverview: houseNavigation.itemOverview,
  navItemResearch: houseNavigation.itemResearch,
  navItemAccount: houseNavigation.itemAccount,
  navItemWorkspace: houseNavigation.itemWorkspace,
  navItemData: houseNavigation.itemData,
  navItemManuscript: houseNavigation.itemManuscript,
  navItemGovernance: houseNavigation.itemGovernance,
  navItemMetaGroup: houseNavigation.itemMetaGroup,
  navItemMeta: houseNavigation.itemMeta,
  navItemCount: houseNavigation.itemCount,
  tableShell: houseSurfaces.tableShell,
  tableHead: houseSurfaces.tableHead,
  tableRow: houseSurfaces.tableRow,
  chartPanel: houseMotion.chartPanel,
  chartSeriesByKey: houseMotion.chartSeriesByKey,
  chartSeriesBySlot: houseMotion.chartSeriesBySlot,
  chartScaleLayer: houseMotion.chartScaleLayer,
  chartScaleTick: houseMotion.chartScaleTick,
  chartScaleAxisTitle: houseMotion.chartScaleAxisTitle,
  toggleChartBar: houseMotion.toggleChartBar,
  toggleChartSwap: houseMotion.toggleChartSwap,
  toggleChartLabel: houseMotion.toggleChartLabel,
  chartGrid: houseChartColors.gridLine,
  chartGridDashed: houseChartColors.gridLineDashed,
  chartGridSubtle: houseChartColors.gridLineSubtle,
  chartGridDashedSubtle: houseChartColors.gridLineDashedSubtle,
  chartMeanLine: houseChartColors.meanLine,
  chartAxisText: houseChartColors.axisText,
  chartAxisLabel: houseChartColors.axisLabel,
  chartAxisSubtext: houseChartColors.axisSubtext,
  chartAxisWindowSubtext: houseChartColors.axisWindowSubtext,
  chartLineSoftSvg: houseChartColors.lineSoftSvg,
  chartRingTrackSvg: houseChartColors.ringTrackSvg,
  chartRingMainSvg: houseChartColors.ringMainSvg,
  chartRingSoftSvg: houseChartColors.ringSoftSvg,
  chartMiniDonut: houseChartColors.miniDonut,
  drilldownSheet: houseDrilldown.sheet,
  drilldownTitleBlock: houseDrilldown.titleBlock,
  drilldownHeadingBlock: houseDrilldown.headingBlock,
  drilldownSubheadingBlock: houseDrilldown.subheadingBlock,
  drilldownContentBlock: houseDrilldown.contentBlock,
  drilldownTitle: houseDrilldown.title,
  drilldownTitleExpander: houseDrilldown.titleExpander,
  drilldownTabTrigger: houseDrilldown.tabTrigger,
  drilldownTabList: houseDrilldown.tabList,
  drilldownPlaceholder: houseDrilldown.placeholder,
  drilldownAlert: houseDrilldown.alert,
  drilldownMicroValue: houseDrilldown.microValue,
  drilldownHint: houseDrilldown.hint,
  drilldownCaption: houseDrilldown.caption,
  drilldownOverline: houseDrilldown.overline,
  drilldownSectionLabel: houseDrilldown.sectionLabel,
  drilldownChip: houseDrilldown.chip,
  drilldownChipActive: houseDrilldown.chipActive,
  drilldownAction: houseDrilldown.action,
  drilldownRow: houseDrilldown.row,
  drilldownRowActive: houseDrilldown.rowActive,
  drilldownProgressTrack: houseDrilldown.progressTrack,
  drilldownProgressFill: houseDrilldown.progressFill,
  drilldownSheetBody: houseDrilldown.sheetBody,
  drilldownStatCard: houseDrilldown.statCard,
  drilldownStatTitle: houseDrilldown.statTitle,
  drilldownStatValue: houseDrilldown.statValue,
  drilldownStatValueEmphasis: houseDrilldown.statValueEmphasis,
  drilldownValuePositive: houseDrilldown.valuePositive,
  drilldownValueNegative: houseDrilldown.valueNegative,
  drilldownAxis: houseDrilldown.axis,
  drilldownRange: houseDrilldown.range,
  drilldownBadge: houseDrilldown.badge,
  drilldownBadgePositive: houseDrilldown.badgePositive,
  drilldownBadgeWarning: houseDrilldown.badgeWarning,
  drilldownBadgeNeutral: houseDrilldown.badgeNeutral,
  drilldownNote: houseDrilldown.note,
  drilldownNoteSoft: houseDrilldown.noteSoft,
  drilldownNoteWarning: houseDrilldown.noteWarning,
  drilldownLink: houseDrilldown.link,
  drilldownOwner: houseDrilldown.owner,
  drilldownFileDrop: houseDrilldown.fileDrop,
  drilldownFileDropActive: houseDrilldown.fileDropActive,
  drilldownDividerTop: houseDrilldown.dividerTop,
  drilldownChartGridSvg: houseDrilldown.chartGridSvg,
  drilldownChartAreaSvg: houseDrilldown.chartAreaSvg,
  drilldownChartMovingSvg: houseDrilldown.chartMovingSvg,
  drilldownChartMainSvg: houseDrilldown.chartMainSvg,
  drilldownChartTooltip: houseDrilldown.chartTooltip,
  drilldownSummaryStatValue: houseDrilldown.summaryStatValue,
  drilldownSummaryStatValueEmphasis: houseDrilldown.summaryStatValueEmphasis,
  drilldownSkeletonBlock: houseDrilldown.skeletonBlock,
  drilldownBarSelected: houseDrilldown.barSelected,
  drilldownBarSelectedOutline: houseDrilldown.barSelectedOutline,
  drilldownTableRow: houseDrilldown.tableRow,
  drilldownTableEmpty: houseDrilldown.tableEmpty,
  drilldownToggleButtonMuted: houseDrilldown.toggleButtonMuted,
  drilldownCollapsibleSection: houseDrilldown.collapsibleSection,
  drilldownCollapsibleEntity: houseDrilldown.collapsibleEntity,
  drilldownSummaryStatsGrid: houseDrilldown.summaryStatsGrid,
  drilldownSummaryStatsGridCompact: houseDrilldown.summaryStatsGridCompact,
  drilldownSummaryTrendChart: houseDrilldown.summaryTrendChart,
  drilldownChartControlsRow: houseDrilldown.chartControlsRow,
  drilldownChartControlsLeft: houseDrilldown.chartControlsLeft,
  drilldownChartMeta: houseDrilldown.chartMeta,
} as const
